### ISSUE TITLE
How to configure it

### ISSUE THREAD

**Issue by grimpa** [yantrashala/loopback-audit-trail#6]
Hi,

How does it work?
How do I configure this package?
Which data does it save? Where does save this data?

Thanks.

**Comment by rjrahul** [comment]
Added description in README. Please check the package main page. To answer your questions

> How does it work?

It attaches remote methods (afterRemote and afterRemoteError) to all loopback models and captures the audit data from context there.

> How do I configure this package?

Refer main page of the package.

> Which data does it save?

Refer main page of the package.

> Where does save this data?

It uses bunyan logger stream to write data. Therefore, it is flexible to save data wherever and however you want. Additionally, since it uses bunyan you can add serializers to bunyan logger to mask the data arguments that may be sensitive information.
